name: Build OpenBIOS

on:
  push:
    # Build for non-release tags only
    branches:
      - "*"
    tags:
      - "!v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: OpenBIOS build for wii-ppc
    container:
      image: ghcr.io/openbios/openbios-builder:master
    steps:
      - name: Checkout OpenBIOS
        uses: actions/checkout@v4

      - name: Backup Makefile.target
        run: cp Makefile.target Makefile.target.orig

      - name: Configure debug
        run: |
          cat Makefile.target.orig | sed 's#CFLAGS+= -Os#CFLAGS+= -O0#g' > Makefile.target
          ./config/scripts/switch-arch wii-ppc

      - name: Build debug
        run: "make V=1"

      - name: Move debug build
        run: "mkdir -p debug && mv obj-* debug"

      - name: Configure release
        run: |
          cp Makefile.target.orig Makefile.target
          ./config/scripts/switch-arch wii-ppc

      - name: Build release
        run: "make V=1"

      - name: Move release build
        run: "mkdir -p release && mv obj-* release"

      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: openbios-wii-latest
          path: |
            debug/obj-ppc/*.dict
            debug/obj-ppc/openbios-wii*
            debug/obj-ppc/Wii,GX2.bin
            release/obj-ppc/*.dict
            release/obj-ppc/openbios-wii*
            release/obj-ppc/Wii,GX2.bin
